version: "3"
services:
  controller:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
      HOSTNAME: "${HOSTNAME}"
    hostname: controller
    image: jrcichra/smartcar_controller
    restart: always
    volumes:
      - "${PWD}/test_config.yml:/config.yml"
    build: ./containers/controller
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
      HOSTNAME: "${HOSTNAME}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio
    depends_on:
      - controller
    build: ./containers/gpio
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    privileged: true
    depends_on:
      - controller
    build: ./containers/dashcam
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - controller
    build: ./containers/transfer
  nas:
    restart: always
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: nas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"