version: '3'
volumes:
  recordings:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/recordings
services:
  redis:
   hostname: redis
   image: jrcichra/redisjson
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
   hostname: dashcam
   image: jrcichra/smartcar_dashcam
   volumes:
    - type: volume
      source: recordings
      target: /recordings
   depends_on:
      - controller
  gpio:
   hostname: gpio
   image: jrcichra/smartcar_gpio
   depends_on:
      - controller
  transfer:
   hostname: transfer
   image: jrcichra/smartcar_transfer
   volumes:
    - type: volume
      source: recordings
      target: /recordings
   depends_on:
      - controller