version: "3"
services:
  # Karmen should be started on the host with 'go build && ./controller'
  # https://github.com/Ircama/ELM327-emulator for OBDII (make handles this)
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio
    build: ./containers/gpio
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
    privileged: true
    build: ./containers/dashcam
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    build: ./containers/transfer
  obdii:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: obdii
    restart: always
    image: jrcichra/smartcar_obdii
    privileged: true
    build: ./containers/obdii
  nas:
    restart: always
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: nas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"