version: "3"
services:
  controller:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: controller
    image: jrcichra/smartcar_controller
    restart: always
    volumes:
      - "${PWD}/new_config.yml:/config.yml"
    build: ./containers/controller2
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    privileged: true
    depends_on:
      - controller
    build: ./containers/dashcam
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio
    depends_on:
      - controller
    build: ./containers/gpio
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - controller
    build: ./containers/transfer
  # cinas:
  #   restart: always
  #   environment:
  #     TZ: "America/New_York"
  #     GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
  #   hostname: cinas
  #   image: rastasheep/ubuntu-sshd
  #   volumes:
  #     - "${PWD}/nas:/recordings"
