version: '3'
services:
  redis:
   hostname: redis
   image: jrcichra/redisjson
  controller:
    hostname: controller
    image: jrcichra/smartcar_controller
    volumes:
      - "${PWD}/config.yml:/config.yml"
    depends_on:
      - redis
  dashcam:
   hostname: dashcam
   image: jrcichra/smartcar_dashcam
   depends_on:
      - controller
  test_client:
   hostname: gpio
   image: jrcichra/smartcar_test_gpio
   depends_on:
      - controller