name: smartcar CI/CD
on:
  push:
    branches:    
    - master         # Push events on master branch

jobs:
  build-test-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build & push
        run: |
          bash -x build.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: test smartcar
        run: |
          mkdir ${PWD}/recordings
          mkdir -p ${PWD}/nas/.convert
          docker-compose -f docker-compose-test.yml up &
          sleep 240
          ls -lrth "${PWD}/recordings"
  build-rpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build & push
        run: |
          bash -x build.sh rpi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: test smartcar rpi
        run: |
          mkdir ${PWD}/recordings
          mkdir -p ${PWD}/nas/.convert
          docker-compose -f docker-compose-test.yml up &
          sleep 240
          ls -lrth "${PWD}/recordings"
